require 'capistrano/multiproject/configurations'
require 'capistrano/multiproject/ensure'
require 'capistrano/multiproject/any_server_role'
require 'capistrano/multiproject/filter_roles'
require 'capistrano/multiproject/task_list'
